CREATE DATABASE IF NOT EXISTS attendance;

USE attendance;

CREATE TABLE IF NOT EXISTS departments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS positions (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS devices ( 
	id INT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) UNIQUE,
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL ,
    device_id INT, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS shifts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(255) UNIQUE,
  fullname VARCHAR(255) NOT NULL DEFAULT 'new employee',
  phone VARCHAR(50),
  email VARCHAR(255),
  shift_id INT,
  department_id INT,
  position_id INT,
  device_id VARCHAR(255),
  faceBase64 TEXT,
  registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS checkins (
	  id INT AUTO_INCREMENT PRIMARY KEY,
    external_id VARCHAR(255),
    checkin_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    employee_ex_id VARCHAR(255),
    device_ex_id VARCHAR(255),
    faceBase64 TEXT,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS shiftrecords (
  id INT AUTO_INCREMENT PRIMARY KEY,
  checkin TIMESTAMP,
  checkout TIMESTAMP,
  employee_id INT,
  shift_id INT,
  checkin_status ENUM('on-time', 'late', 'absent', 'Unassigned'),
  checkout_status ENUM('on-time', 'early-leave', 'absent', 'Unassigned'),
  time DATE
);
